import type { Metadata } from "next";
import { IRANSansX } from "./fonts";
import { Toaster as Sonner } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${IRANSansX.className}`}>
      <body>
        {children}
        <Sonner richColors closeButton style={IRANSansX.style} />
      </body>
    </html>
  );
}
